### ISSUE TITLE
"de.unifreiburg.unet.DetectionJob.processHyperStack" does not work uising ImageJ Macro

### ISSUE THREAD

**Issue by hanginzer** [lmb-freiburg/Unet-Segmentation#13]
Thank you very much for developing the really great software.

I am trying to run "detection" using ".ijm" (ImageJ Macro), however, 
call("de.unifreiburg.unet.DetectionJob.processHyperStack", ....)
dose not work even though call("de.unifreiburg.unet.SegmentationJob.processHyperStack", ....) perfectly works.

Can we use "de.unifreiburg.unet.DetectionJob"  as ImageJ Macro or it's not supported yet?

The error message is as follows:
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52i; Java 1.8.0_172 [64-bit]; Mac OS X 10.14; 573MB of 8395MB (6%)
 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ij.macro.Functions.call(Functions.java:4379)
	at ij.macro.Functions.getStringFunction(Functions.java:274)
	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1366)
	at ij.macro.Interpreter.getString(Interpreter.java:1344)
	at ij.macro.Interpreter.doStatement(Interpreter.java:304)
	at ij.macro.Interpreter.doStatements(Interpreter.java:236)
	at ij.macro.Interpreter.run(Interpreter.java:119)
	at ij.macro.Interpreter.run(Interpreter.java:90)
	at ij.macro.Interpreter.run(Interpreter.java:101)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.IJ.runMacro(IJ.java:147)
	at ij.IJ.runMacro(IJ.java:136)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1107)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1103)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1054)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1103)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:147)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at de.unifreiburg.unet.DetectionJob.processHyperStack(DetectionJob.java:131)
	... 30 more

**Comment by ThorstenFalk** [comment]
Thanks for reporting this bug. Empty parameters are not handled correctly in this version. The latest update should fix this.

**Comment by hanginzer** [comment]
Thank you so much.
