### ISSUE TITLE
Exception in thread "Thread-5" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by HyacintViolet** [lmb-freiburg/Unet-Segmentation#75]
Hi, I'm trying to finetune a model lately.
While the finetune module works perfectly fine on the sampledata/DIC-Erythrocytes provided by your website, it throws an exception on my own data once it starts:

> Exception in thread "Thread-5" java.lang.IllegalArgumentException: n out of range: 2
	at ij.ImagePlus.convertIndexToPosition(ImagePlus.java:1824)
	at de.unifreiburg.unet.TrainingSample.getROIPosition(TrainingSample.java:1656)
	at de.unifreiburg.unet.TrainingSample.createLabelsAndWeightBlobsFromRois(TrainingSample.java:1256)
	at de.unifreiburg.unet.TrainingSample.createLabelsAndWeightsBlobs(TrainingSample.java:195)
	at de.unifreiburg.unet.FinetuneJob.run(FinetuneJob.java:1983)

And the log window halts at:
![unet_exception](https://user-images.githubusercontent.com/12589928/97967306-02bd7e00-1df8-11eb-9902-84d9fa25ee55.png)

Info of my image:
![unet_exception_image](https://user-images.githubusercontent.com/12589928/97967360-10730380-1df8-11eb-8dd1-96ca1182431c.png)

Any idea what might went wrong?

**Comment by HyacintViolet** [comment]
I figured it out myself.
When I was labeling my data pictures I made a stack of two channels, in order to check the accuracy of my labeling.
Reverting to labeling on single channel data resolved the problem.
