### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by phischer007** [lmb-freiburg/Unet-Segmentation#92]
Hi, I am currently trying to use U-Net Segmentation for Deep Learning. However, after following the installations procedure (Setup on own server (from source)); I encountered an issue related to caffe. Below are the details of the server

- Ubuntu 18.04
- NVIDIA GeForce RTX 3090
- Multiply CUDA (CUDA 10.0 & CUDA 11.4)
- cuDNN version 7.6.5

`**Error Message** : caffe : symbol lookup error : undefined symbol : __ZN5Caffe3NetIfE2CopyTrainedLayersFromENSt7 __cxx1112basic_stringIcSt11char_traitsIcSaIcEEE `

In addition, after an installation or update of Fiji U-Net Segmentation, whenever you click on "segmentation or fine tunning"; the error below appears 
```
Exception in thread “AWT-EventQueue-0” java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
at de.unifreiburg.unet.JobTableModel.createFinetuneJob(JobTableModel.java:129)
at de.unifreiburg.unet.JobManager$3.actionPerformed(JobManager.java:125)
at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)

```
Many thanks!

**Comment by Hir320** [comment]
The second error occurred in my Fiji as well.

Here is the error messages:

`xception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
	at de.unifreiburg.unet.JobTableModel.createSegmentationJob(JobTableModel.java:121)
	at de.unifreiburg.unet.JobManager$1.actionPerformed(JobManager.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: ncsa.hdf.hdf5lib.exceptions.HDF5Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
	at de.unifreiburg.unet.JobTableModel.createSegmentationJob(JobTableModel.java:121)
	at de.unifreiburg.unet.JobManager$1.actionPerformed(JobManager.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: ncsa.hdf.hdf5lib.exceptions.HDF5Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
	at de.unifreiburg.unet.JobTableModel.createSegmentationJob(JobTableModel.java:121)
	at de.unifreiburg.unet.JobManager$1.actionPerformed(JobManager.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: ncsa.hdf.hdf5lib.exceptions.HDF5Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
	at de.unifreiburg.unet.JobTableModel.createSegmentationJob(JobTableModel.java:121)
	at de.unifreiburg.unet.JobManager$1.actionPerformed(JobManager.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: ncsa.hdf.hdf5lib.exceptions.HDF5Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
`

This happened even when the remote server was not connected, so I suppose this problem is in the local PC.

**Comment by ThorstenFalk** [comment]
The latter should be solved by updating the plugin. With Fiji updating jhdf5, adaptations were necessary.

**Comment by ThorstenFalk** [comment]
The first problem seems to be path-related. Your system does not find any or the wrong libcaffe.so.0. Please check your LD_LIBRARY_PATH environment variable. If you have another caffe installation, e.g. via apt install, you must set PATH and LD_LIBRARY_PATH, so that the caffe binary and the libcaffe.so.0 library from your caffe_unet installation is found first.

`which caffe` will show you the path to caffe in your shell
`ldd $(which caffe)` will show paths to all found reqired libraries and tell you if a library is missing.

**Comment by phischer007** [comment]
> The first problem seems to be path-related. Your system does not find any or the wrong libcaffe.so.0. Please check your LD_LIBRARY_PATH environment variable. If you have another caffe installation, e.g. via apt install, you must set PATH and LD_LIBRARY_PATH, so that the caffe binary and the libcaffe.so.0 library from your caffe_unet installation is found first.
> 
> `which caffe` will show you the path to caffe in your shell `ldd $(which caffe)` will show paths to all found reqired libraries and tell you if a library is missing.

@ThorstenFalk thank you for your response. In addition, I used multiple CUDA version (CUDA 10.0 & 11.4) , is this advisable or I should use the CUDA version that corresponds with my NVIDIA card 
- `nvidia-smi (NVIDIA-SMI: 470.141.03 Driver Version: 470.141.03 CUDA Version: 11.4 with cuDNN 7.6.5)`

The reason I installed CUDA 10.0 was due to the information on the U-NET webpage (https://lmb.informatik.uni-freiburg.de/resources/opensource/unet/) but when I test the cuDNN (/usr/src/cudnn_samples_v7/mnistCUDNN) : the test fails.

**Comment by phischer007** [comment]
> > The first problem seems to be path-related. Your system does not find any or the wrong libcaffe.so.0. Please check your LD_LIBRARY_PATH environment variable. If you have another caffe installation, e.g. via apt install, you must set PATH and LD_LIBRARY_PATH, so that the caffe binary and the libcaffe.so.0 library from your caffe_unet installation is found first.
> > `which caffe` will show you the path to caffe in your shell `ldd $(which caffe)` will show paths to all found reqired libraries and tell you if a library is missing.
> 
> @ThorstenFalk thank you for your response. After checking and modifying what you posted; `caffe_unet` working prefect on the backend server however, it cannot function properly via **SSH** so when I tried connecting to the backend server with Fiji neither `caffe` or `caffe_unet` works. Any solution would be appreciated.

**Comment by phischer007** [comment]
@ThorstenFalk Is it a good idea to use multiple CUDA version with `caffe_unet` because after installing my NVIDIA card the recommended CUDA was `version 11.4` however the tutorial on your website stated that `caffe + u-net` was tested on  CUDA Toolkit 8/9/10 with its matching `cuDNN versions` on Ubuntu 16.04/18.04.

**Comment by ThorstenFalk** [comment]
No guarantees regarding compatibility of CUDA 10 with your GPU, the newest one I can access is a TitanXP. I experience no problem with multiple CUDA Versions. caffe_unet will search for the version you linked to at time of build. With pre-built binaries you need the version compination of CUDA and cuDNN stated on the website.

**Comment by Hir320** [comment]
> The latter should be solved by updating the plugin. With Fiji updating jhdf5, adaptations were necessary.

The update solved my problem. Thank you so much!

**Comment by phischer007** [comment]
@ThorstenFalk I have been successfully install 

> No guarantees regarding compatibility of CUDA 10 with your GPU, the newest one I can access is a TitanXP. I experience no problem with multiple CUDA Versions. caffe_unet will search for the version you linked to at time of build. With pre-built binaries you need the version compination of CUDA and cuDNN stated on the website.

**Comment by phischer007** [comment]
> No guarantees regarding compatibility of CUDA 10 with your GPU, the newest one I can access is a TitanXP. I experience no problem with multiple CUDA Versions. caffe_unet will search for the version you linked to at time of build. With pre-built binaries you need the version compination of CUDA and cuDNN stated on the website.

@ThorstenFalk I have successfully installed however, when I run Fiji - U-Net Segmentation Job Manager, caffe uses the CPU not the GPU. Please any recommendation would be appreciated.
Thank you
